[package]
name = "emb1"
version = "0.1.0"
authors = ["cbiffle <code@cliffle.com>"]

[dependencies]
rust-libcore = "*"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
